---
- name: Ensure Apache is installed.
  apt: name={{ item }} state=present
  with_items:
       - apache2
       - "{{apache_packages}}"
- name: LINEINFILE | Change port
  lineinfile:
    dest: /etc/apache2/ports.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
       - {
         regexp: "^Listen ",
         line: "Listen {{ apache_listen_port }}"
       }
       - {
         regexp: "^NameVirtualHost ",
         line: "NameVirtualHost 127.0.0.1:{{ apache_listen_port }}"
       }
  notify: restart apache
- name: SHELL | Enable Apache mods.
  shell: a2enmod {{ item }}
  with_items: apache_mods_enabled
  notify: restart apache
- name: FILE | Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest:  /etc/apache2/sites-available/{{ apache_vhosts_filename }}
    owner: root
    group: root
    mode: 0644
  notify: restart apache
- name: SHELL | Enable vhosts
  shell: a2ensite {{ apache_vhosts_filename }}
- name: Ensure Apache is started and enabled on boot.
  service:
    name: apache2
    state: started
    enabled: yes
